### ISSUE TITLE
Functions/methods that throws error

### ISSUE THREAD

**Issue by cedlemo** [cedlemo/OCaml-GObject-Introspection#20]
Create a type : 

``` 
type greturn = Ok of 'a | Error of GLib.Error.t ptr
```

in the automatic process, try to generate a function that : 
* has all the arguments of the C function/method minus the GError argument
* allocates a new `GLib.Error.t ` with `Gc.finalize`
* encapsulates the raw bindings
* call the raw bindings with GLib.Error.t
* returns `Error e` when the GLib.Error.t ptr is not null or return `Ok ret_value`

**Comment by yallop** [comment]
How about using the [new standard result type](https://github.com/ocaml/ocaml/blob/7b1140f10abb41953d8ca8f030c192d406f49ebf/stdlib/pervasives.mli#L1087) for this?

```ocaml
type ('a,'b) result = Ok of 'a | Error of 'b
```

i.e. define

```ocaml
type 'a greturn = ('a, GLib.Error.t ptr) result
```

**Comment by cedlemo** [comment]
@yallop,

of course, I did not know about it, thanks. How does it work with Ctypes ? is there a specific view for the result type?

**Comment by yallop** [comment]
There's no specific support for `result` in Ctypes at the moment -- it's tricky to do something completely general, since there are so many different (and mutually incompatible) ways of reporting errors.

**Comment by cedlemo** [comment]
@yallop,

I am a little lost with the result type for example you tell me to define a new type with

    type 'a greturn = ('a, GLib.Error.t ptr) result

but when I do some tests in utop : 

```
utop # type 'a greturn = ('a, string) result;;
type 'a greturn = ('a, string) result
utop # let t str =
match str with 
| "toto" -> Error (-1)
| _ -> Ok str;;
val t : string -> (string, int) result = <fun> 
```

I expected that with the type inference, the signature of t will be : 

    val t : string -> string greturn = <fun>

It seems that I don't know how to use the `result` type, should I really need to create the type `greturn` ?

**Comment by yallop** [comment]
> It seems that I don't know how to use the result type, should I really need to create the type greturn ?

No, there's no need -- `greturn` is just an alias.  It's fine (and perhaps clearer) to use `result` directly instead.
